from typing import Literal

from fastapi import APIRouter, Depends, Query, status
from sqlalchemy import func
from sqlalchemy.orm import Session

from app.core.auth import require_roles
from app.db.session import get_db
from app.models.incident import Incident
from app.schemas.alert import AlertCreate, IncidentResponse
from app.schemas.common import ApiResponse
from app.services.alert_service import create_incident_from_alert, get_queue_metrics
from app.soar.option2_simulation.simulate_bruteforce import simulate as sim_bruteforce
from app.soar.option2_simulation.simulate_malware import simulate as sim_malware
from app.soar.option2_simulation.simulate_network_anomaly import simulate as sim_network_anomaly
from app.soar.option2_simulation.simulate_phishing import simulate as sim_phishing

router = APIRouter(prefix="/simulations", dependencies=[Depends(require_roles("admin", "analyst"))])

SimulationType = Literal["brute-force", "phishing", "malware", "network-anomaly", "all"]
CONTRACT_VERSION = "v1"
PIPELINE_FLOW = ["simulation", "incident", "queue", "playbook", "result"]


def _lifecycle_states() -> dict[str, list[str]]:
    return {
        "incident_status": ["open", "closed", "failed"],
        "playbook_status": ["pending", "running", "success", "failed"],
    }


def _to_incident_payload(sim_alert: dict, created_by: int | None) -> AlertCreate:
    alert_type = str(sim_alert.get("alert_type", "simulation_alert"))
    source = str(sim_alert.get("source", "option2_simulation"))
    severity = str(sim_alert.get("severity", "medium"))

    title = alert_type.replace("_", " ").title()
    description = f"Generated by simulation endpoint: {alert_type}"

    return AlertCreate(
        title=title,
        source=source,
        severity=severity,
        description=description,
        raw_alert=sim_alert,
        created_by=created_by,
    )


def _run_single_simulation(simulation_type: SimulationType, count: int) -> list[dict]:
    if simulation_type == "brute-force":
        _, alerts = sim_bruteforce(num_attempts=count)
        return alerts
    if simulation_type == "phishing":
        _, alerts = sim_phishing(num_emails=count)
        return alerts
    if simulation_type == "malware":
        _, alerts = sim_malware(num_files=count)
        return alerts
    if simulation_type == "network-anomaly":
        _, alerts = sim_network_anomaly(num_traffic=count)
        return alerts

    if simulation_type == "all":
        all_alerts: list[dict] = []
        all_alerts.extend(_run_single_simulation("brute-force", count))
        all_alerts.extend(_run_single_simulation("phishing", count))
        all_alerts.extend(_run_single_simulation("malware", count))
        all_alerts.extend(_run_single_simulation("network-anomaly", count))
        return all_alerts

    return []


@router.post("/{simulation_type}", response_model=ApiResponse, status_code=status.HTTP_201_CREATED)
def run_simulation(
    simulation_type: SimulationType,
    db: Session = Depends(get_db),
    count: int = Query(default=10, ge=1, le=100),
    created_by: int | None = Query(default=None),
) -> ApiResponse:
    simulated_alerts = _run_single_simulation(simulation_type=simulation_type, count=count)

    incidents: list[dict] = []
    incident_ids: list[int] = []
    for sim_alert in simulated_alerts:
        payload = _to_incident_payload(sim_alert=sim_alert, created_by=created_by)
        incident = create_incident_from_alert(db=db, alert=payload)
        incident_ids.append(incident.id)
        incidents.append(IncidentResponse.model_validate(incident).model_dump(mode="json"))

    queue_snapshot = get_queue_metrics(db)

    return ApiResponse(
        message="Simulation executed and incidents queued for playbook processing",
        data={
            "contract_version": CONTRACT_VERSION,
            "pipeline_flow": PIPELINE_FLOW,
            "lifecycle_states": _lifecycle_states(),
            "simulation_type": simulation_type,
            "requested_count": count,
            "alerts_generated": len(simulated_alerts),
            "incidents_created": len(incidents),
            "incident_ids": incident_ids,
            "latest_incident_id": incident_ids[-1] if incident_ids else None,
            "incidents": incidents,
            "queue": queue_snapshot,
        },
    )


@router.get("/summary", response_model=ApiResponse)
def simulation_summary(
    db: Session = Depends(get_db),
    limit: int = Query(default=10, ge=1, le=100),
) -> ApiResponse:
    base_query = db.query(Incident).filter(Incident.source == "option2_simulation")

    total_incidents = base_query.count()

    severity_rows = (
        db.query(Incident.severity, func.count(Incident.id))
        .filter(Incident.source == "option2_simulation")
        .group_by(Incident.severity)
        .all()
    )
    severity_breakdown = {str(severity): count for severity, count in severity_rows}

    playbook_status_rows = (
        db.query(Incident.playbook_status, func.count(Incident.id))
        .filter(Incident.source == "option2_simulation")
        .group_by(Incident.playbook_status)
        .all()
    )
    playbook_status_breakdown = {
        str(playbook_status): count for playbook_status, count in playbook_status_rows
    }

    incident_status_rows = (
        db.query(Incident.status, func.count(Incident.id))
        .filter(Incident.source == "option2_simulation")
        .group_by(Incident.status)
        .all()
    )
    incident_status_breakdown = {str(incident_status): count for incident_status, count in incident_status_rows}

    recent_incidents = (
        base_query.order_by(Incident.created_at.desc()).limit(limit).all()
    )
    serialized_recent = [
        IncidentResponse.model_validate(incident).model_dump(mode="json") for incident in recent_incidents
    ]

    queue_snapshot = get_queue_metrics(db)

    return ApiResponse(
        message="Simulation incident summary fetched successfully",
        data={
            "contract_version": CONTRACT_VERSION,
            "pipeline_flow": PIPELINE_FLOW,
            "lifecycle_states": _lifecycle_states(),
            "source": "option2_simulation",
            "total_incidents": total_incidents,
            "severity_breakdown": severity_breakdown,
            "playbook_status_breakdown": playbook_status_breakdown,
            "incident_status_breakdown": incident_status_breakdown,
            "recent_count": len(serialized_recent),
            "recent_incidents": serialized_recent,
            "queue": queue_snapshot,
        },
    )


@router.get("/queue-metrics", response_model=ApiResponse)
def simulation_queue_metrics(
    db: Session = Depends(get_db),
    window_hours: int = Query(default=24, ge=1, le=24 * 30),
) -> ApiResponse:
    return ApiResponse(
        message="Simulation queue metrics fetched successfully",
        data={"queue": get_queue_metrics(db, window_hours=window_hours)},
    )
