# utils/reporter.py
# PDF Incident Report Generator
# Follows NIST SP 800-61 Incident Report Format

import copy
import json
import logging
import os
from datetime import datetime

from fpdf import FPDF
from fpdf.enums import XPos, YPos

SUPPORTED_REPORT_PROFILES = {"full", "redacted"}
logger = logging.getLogger(__name__)


def resolve_report_profile(profile: str | None) -> str:
    requested = (profile or os.getenv("SOAR_REPORT_PROFILE", "full")).strip().lower()
    return requested if requested in SUPPORTED_REPORT_PROFILES else "full"


def _mask_ip(value):
    if not isinstance(value, str):
        return value

    parts = value.split(".")
    if len(parts) == 4 and all(part.isdigit() for part in parts):
        return ".".join(parts[:3] + ["x"])

    return "[redacted]"


def _redact_alert_details(alert_details):
    if not isinstance(alert_details, dict):
        return {}

    redacted = {}
    for key, value in alert_details.items():
        lowered = key.lower()

        if lowered.endswith("_ip") or lowered in {"ip", "src_ip", "dst_ip", "target_ip", "attacker_ip"}:
            redacted[key] = _mask_ip(value)
        elif lowered in {"usernames_tried", "username", "sender", "recipient", "email"}:
            redacted[key] = "[redacted]"
        elif lowered in {"url", "domain", "hostname", "host"}:
            redacted[key] = "[redacted]"
        else:
            redacted[key] = value

    return redacted


def _redact_threat_intel(threat_intel):
    if not isinstance(threat_intel, dict):
        return {}

    redacted = {}
    for provider, data in threat_intel.items():
        if not isinstance(data, dict):
            redacted[provider] = data
            continue

        provider_data = copy.deepcopy(data)
        if "ip" in provider_data:
            provider_data["ip"] = _mask_ip(provider_data.get("ip"))
        if "country" in provider_data:
            provider_data["country"] = "[redacted]"
        if "isp" in provider_data:
            provider_data["isp"] = "[redacted]"
        redacted[provider] = provider_data

    return redacted


def _redact_response_actions(actions):
    if not isinstance(actions, list):
        return []

    redacted_actions = []
    for entry in actions:
        if isinstance(entry, dict):
            redacted_actions.append(
                {
                    "action": "[redacted]",
                    "timestamp": entry.get("timestamp"),
                    "status": entry.get("status", "COMPLETED"),
                }
            )
        else:
            redacted_actions.append("[redacted]")

    return redacted_actions


def apply_report_profile(report_data, profile=None):
    resolved_profile = resolve_report_profile(profile)
    normalized = copy.deepcopy(report_data) if isinstance(report_data, dict) else {}

    if resolved_profile == "full":
        normalized.setdefault("report_profile", "full")
        return normalized

    normalized["alert_details"] = _redact_alert_details(normalized.get("alert_details", {}))
    normalized["threat_intel"] = _redact_threat_intel(normalized.get("threat_intel", {}))
    normalized["response_taken"] = _redact_response_actions(normalized.get("response_taken", []))
    normalized["report_profile"] = "redacted"
    logger.info(
        "artifact_profile_applied",
        extra={
            "incident_id": normalized.get("incident_id"),
            "report_profile": "redacted",
        },
    )
    return normalized


class IncidentReportPDF(FPDF):
    """Custom PDF class with header and footer"""

    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.set_fill_color(30, 30, 30)
        self.set_text_color(255, 255, 255)
        self.cell(
            0,
            15,
            "SOAR PLATFORM - INCIDENT REPORT",
            border=0,
            new_x=XPos.LMARGIN,
            new_y=YPos.NEXT,
            align="C",
            fill=True,
        )
        self.set_text_color(0, 0, 0)
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(
            0,
            10,
            f"CONFIDENTIAL | Generated by SOAR Platform | Page {self.page_no()}",
            border=0,
            new_x=XPos.RIGHT,
            new_y=YPos.TOP,
            align="C",
        )
        self.set_text_color(0, 0, 0)


class ReportGenerator:
    """
    Generates PDF incident reports
    Following NIST SP 800-61 format
    """

    def __init__(self):
        self.report_dir = os.getenv("SOAR_REPORTS_DIR", os.path.join(os.getcwd(), "reports"))
        os.makedirs(self.report_dir, exist_ok=True)

    def _sanitize(self, text):
        """Remove non-latin characters that PDF can't encode"""
        return str(text).encode("latin-1", errors="replace").decode("latin-1")

    def _get_severity_color(self, severity):
        colors = {
            "CRITICAL": (220, 50, 50),
            "HIGH": (220, 120, 50),
            "MEDIUM": (220, 180, 50),
            "LOW": (50, 150, 50),
        }
        return colors.get(severity, (100, 100, 100))

    def _add_section_header(self, pdf, title):
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_fill_color(50, 50, 50)
        pdf.set_text_color(255, 255, 255)
        pdf.cell(0, 10, f"  {title}", border=0, new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="L", fill=True)
        pdf.set_text_color(0, 0, 0)
        pdf.ln(2)

    def _add_field(self, pdf, label, value):
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(60, 8, self._sanitize(f"{label}:"), border=0, new_x=XPos.RIGHT, new_y=YPos.TOP)
        pdf.set_font("Helvetica", "", 10)
        str_value = self._sanitize(str(value))
        if len(str_value) > 80:
            str_value = str_value[:77] + "..."
        pdf.cell(0, 8, str_value, border=0, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    def generate(self, report_data):
        pdf = IncidentReportPDF()
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=15)

        severity = report_data.get("severity", "LOW")
        incident_id = report_data.get("incident_id", "UNKNOWN")

        self._add_section_header(pdf, "1. INCIDENT OVERVIEW")

        r, g, b = self._get_severity_color(severity)
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_fill_color(r, g, b)
        pdf.set_text_color(255, 255, 255)
        pdf.cell(0, 12, f"  SEVERITY: {severity}", border=0, new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="L", fill=True)
        pdf.set_text_color(0, 0, 0)
        pdf.ln(3)

        self._add_field(pdf, "Incident ID", incident_id)
        self._add_field(pdf, "Playbook", report_data.get("playbook_name", ""))
        self._add_field(pdf, "Alert Type", report_data.get("alert_type", ""))
        self._add_field(pdf, "MITRE Technique", report_data.get("mitre_technique", ""))
        self._add_field(pdf, "Risk Score", f"{report_data.get('risk_score', 0)}/100")
        self._add_field(pdf, "Status", report_data.get("status", ""))
        self._add_field(pdf, "Data Source", report_data.get("source", ""))
        self._add_field(pdf, "Report Profile", report_data.get("report_profile", "full"))
        self._add_field(pdf, "Start Time", report_data.get("start_time", ""))
        self._add_field(pdf, "End Time", report_data.get("end_time", ""))
        pdf.ln(5)

        self._add_section_header(pdf, "2. ALERT DETAILS  (NIST: Detection & Analysis)")

        alert_details = report_data.get("alert_details", {})
        if alert_details:
            for key, value in alert_details.items():
                self._add_field(pdf, key.replace("_", " ").title(), str(value))
        else:
            pdf.set_font("Helvetica", "I", 10)
            pdf.cell(0, 8, "No alert details available", border=0, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.ln(5)

        self._add_section_header(pdf, "3. THREAT INTELLIGENCE RESULTS")

        threat_intel = report_data.get("threat_intel", {})
        if threat_intel:
            for tool, data in threat_intel.items():
                if isinstance(data, dict):
                    pdf.set_font("Helvetica", "B", 10)
                    pdf.cell(0, 8, f"  [{tool.upper()}]", border=0, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
                    pdf.set_font("Helvetica", "", 10)
                    summary = data.get("summary", data.get("error", "No data available"))
                    pdf.cell(10, 7, "", border=0, new_x=XPos.RIGHT, new_y=YPos.TOP)
                    pdf.cell(0, 7, f"Result: {str(summary)[:100]}", border=0, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
                    pdf.ln(1)
        else:
            pdf.set_font("Helvetica", "I", 10)
            pdf.cell(0, 8, "No threat intelligence data available", border=0, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.ln(5)

        self._add_section_header(pdf, "4. RESPONSE ACTIONS  (NIST: Containment & Recovery)")

        response_actions = report_data.get("response_taken", [])
        if response_actions:
            for i, action in enumerate(response_actions, 1):
                pdf.set_font("Helvetica", "", 10)
                action_text = str(action.get("action", "")) if isinstance(action, dict) else str(action)
                if len(action_text) > 100:
                    action_text = action_text[:97] + "..."
                action_text = self._sanitize(action_text)
                pdf.cell(0, 7, f"  {i}. {action_text}", border=0, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        self._add_section_header(pdf, "5. RISK ANALYSIS")

        risk_score = report_data.get("risk_score", 0)
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 8, f"Risk Score: {risk_score}/100", border=0, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        pdf.set_fill_color(220, 220, 220)
        pdf.cell(190, 8, "", border=0, new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="L", fill=True)
        pdf.set_y(pdf.get_y() - 8)

        r, g, b = self._get_severity_color(severity)
        pdf.set_fill_color(r, g, b)
        bar_width = max(1, int((risk_score / 100) * 190))
        pdf.cell(bar_width, 8, "", border=0, new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="L", fill=True)
        pdf.ln(3)

        severity_desc = {
            "CRITICAL": "Immediate action required. High confidence attack.",
            "HIGH": "Urgent attention needed. Strong malicious indicators.",
            "MEDIUM": "Investigation recommended. Suspicious activity detected.",
            "LOW": "Low priority. Weak indicators only. Continue monitoring.",
        }

        pdf.set_font("Helvetica", "", 10)
        pdf.cell(
            0,
            7,
            f"Assessment: {severity_desc.get(severity, 'Unknown')}",
            border=0,
            new_x=XPos.LMARGIN,
            new_y=YPos.NEXT,
        )
        pdf.ln(5)

        self._add_section_header(pdf, "6. RECOMMENDATIONS  (NIST: Post-Incident Activity)")

        recommendations = self._get_recommendations(report_data.get("alert_type", ""), severity)

        pdf.set_font("Helvetica", "", 10)
        for i, rec in enumerate(recommendations, 1):
            pdf.cell(0, 7, self._sanitize(f"  {i}. {rec}"), border=0, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        pdf.ln(5)

        self._add_section_header(pdf, "7. REPORT METADATA")

        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(
            0,
            7,
            f"Report Generated : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            border=0,
            new_x=XPos.LMARGIN,
            new_y=YPos.NEXT,
        )
        pdf.cell(0, 7, "Platform         : SOAR Platform v1.0", border=0, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.cell(0, 7, "Framework        : NIST SP 800-61 + MITRE ATT&CK", border=0, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.cell(0, 7, "Classification   : CONFIDENTIAL", border=0, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_text_color(0, 0, 0)

        pdf_path = f"{self.report_dir}/{incident_id}.pdf"
        pdf.output(pdf_path)
        logger.info(
            "artifact_pdf_created",
            extra={
                "incident_id": incident_id,
                "pdf_path": pdf_path,
                "report_profile": report_data.get("report_profile", "full"),
            },
        )
        print(f"  [+] PDF Report saved: {pdf_path}")
        return pdf_path

    def _get_recommendations(self, alert_type, severity):
        recommendations = {
            "BRUTE_FORCE_DETECTED": [
                "Implement account lockout after 3-5 failed attempts",
                "Enable Multi-Factor Authentication on all accounts",
                "Use fail2ban to auto-block attacking IPs",
                "Disable password auth on SSH - use keys only",
                "Monitor login patterns and alert on anomalies",
            ],
            "BRUTE_FORCE_DDOS": [
                "Implement rate limiting on all network endpoints",
                "Deploy DDoS protection service",
                "Configure firewall rules to block suspicious patterns",
                "Set up traffic scrubbing and anomaly detection",
                "Review and update network capacity planning",
            ],
            "PHISHING_URL": [
                "Implement email filtering with anti-phishing",
                "Train employees on phishing awareness",
                "Deploy web proxy with URL filtering",
                "Enable DMARC DKIM and SPF on email domain",
                "Conduct regular phishing simulation exercises",
            ],
            "PHISHING_EMAIL_DETECTED": [
                "Implement email filtering with anti-phishing",
                "Train employees on phishing awareness",
                "Enable DMARC DKIM and SPF on email domain",
                "Deploy sandboxing for email attachments",
                "Conduct regular phishing simulation exercises",
            ],
            "MALWARE_DETECTED": [
                "Update all antivirus and endpoint protection",
                "Implement application whitelisting",
                "Review and restrict user privileges",
                "Enable and monitor Windows Event Logs",
                "Conduct regular vulnerability assessments",
            ],
            "NETWORK_ANOMALY_DETECTED": [
                "Implement network segmentation",
                "Deploy Intrusion Detection System IDS",
                "Review and tighten firewall rules",
                "Enable full packet capture on critical segments",
                "Conduct regular network penetration testing",
            ],
            "NETWORK_ANOMALY": [
                "Implement network segmentation",
                "Deploy IDS/IPS system",
                "Review firewall rules regularly",
                "Enable network traffic monitoring",
                "Conduct regular security audits",
            ],
        }

        default = [
            "Review security policies and procedures",
            "Conduct security awareness training",
            "Implement defense in depth strategy",
            "Regular security audits and penetration testing",
            "Keep all systems and software updated",
        ]

        return recommendations.get(alert_type, default)


def generate_pdf_report(report_data):
    generator = ReportGenerator()
    profiled_report = apply_report_profile(report_data)
    return generator.generate(profiled_report)


if __name__ == "__main__":
    print("\n" + "=" * 60)
    print("   PDF REPORT GENERATOR TEST")
    print("=" * 60)

    report_dir = os.getenv("SOAR_REPORTS_DIR", os.path.join(os.getcwd(), "reports"))

    json_files = [f for f in os.listdir(report_dir) if f.endswith(".json")]

    if not json_files:
        print("[!] No JSON reports found.")
        print("[!] Run a playbook first.")
    else:
        print(f"[*] Found {len(json_files)} JSON reports")
        print("[*] Generating PDFs...\n")

        for json_file in json_files:
            json_path = f"{report_dir}/{json_file}"
            with open(json_path, "r") as f:
                report_data = json.load(f)
            print(f"[*] Processing: {json_file}")
            _ = generate_pdf_report(report_data)

        print(f"\n[*] All PDFs in: {report_dir}")
        print("\n" + "=" * 60)
        print("   PDF GENERATION COMPLETE")
        print("=" * 60)
